#!/bin/bash
echo "HENLOOOO"
echo "HOSTNAME =  $(hostname | awk '{print $0}')"
echo "TIMEZONE =  $(timedatectl | grep 'Time zone' | awk '{print $3 $4 $5}')"
echo "USER =  $(whoami | awk '{print $0}')"
echo "OS =  $(cat /etc/issue | awk '{print $0}')"
echo "DATE =  $(date '+%Y-%m-%d %H:%M:%S')"
echo "UPTIME = $(uptime -p | awk '{print $2 $3}')"
echo "UPTIME_SEC = $(cat /proc/uptime | awk '{print $1}')"
echo "IP = $(hostname -I | awk '{print $0}')"
echo "MASK = $(ifconfig | grep -i mask | head -n 1 | awk '{print $0}')"
echo "GATEWAY =  $(ip route | grep default | awk '{print $3}')"
echo "RAM_TOTAL =  $(free -h -t | grep Mem | awk '{print $2}')"