#!/bin/bash
HOSTNAME=$(hostname | awk '{print $0}')
TIMEZONE=$(timedatectl | grep 'Time zone' | awk '{print $3 $4 $5}')
USER=$(whoami | awk '{print $0}')
OS=$(cat /etc/issue | awk '{print $1 $2 $3}')
DATE=$(date '+%Y-%m-%d %H:%M:%S')
UPTIME=$(uptime -p | awk '{print $2 $3 $4 $5}')
UPTIME_SEC=$(cat /proc/uptime | awk '{print $1}')
IP=$(hostname -I | awk '{print $0}')
MASK=$(ifconfig | grep mask | head -n 1 | awk '{print $4}')
GATEWAY=$(ip route | grep default | awk '{print $3}')
RAM_TOTAL=$(free -m | grep Mem | awk '{printf "%.3fGb\n", $2/1024}')
RAM_USED=$(free -m | grep Mem | awk '{printf "%.3fGb\n", $3/1024}')
RAM_FREE=$(free -m | grep Mem | awk '{printf "%.3fGb\n", $4/1024}')
SPACE_ROOT=$(df /root/ | tail -n 1 | awk '{printf "%.2fMb\n", $2/1024}')
SPACE_ROOT_USED=$(df /root/ | tail -n 1 | awk '{printf "%.2fMb\n", $3/1024}')
SPACE_ROOT_USED=$(df /root/ | tail -n 1 | awk '{printf "%.2fMb\n", $4/1024}')